### ISSUE TITLE
How to configure privilaged, unprivilaged, protected and non-protected values while mitigation

### ISSUE THREAD

**Issue by pradeepdev-1995** [scotthlee/fairness#11]
How to configure privilaged, unprivilaged, protected and non-protected values while mitigation like other tools such as AIF360 are doing? 
Also what are the mitigation techniques(Algorithms) using here?

**Comment by scotthlee** [comment]
Hi! Our code is based on a single kind of mitigation technique--a post-hoc adjustment for enforcing equalized opportunity and odds in binary and multiclass problems that's achieved through linear programming. The binary algorithm is taken from Hardt, Srebro, & Price (2016), and the multiclass algorithm, which extends their binary algorithm, is our own. Both algorithms only allow for a single protected attribute (_A_ in both their paper and ours, with _Y_, _Y_-tilde, and_ _Y_-hat denoting the target and biased and adjusted predictors, respectively). I haven't used AIF360, so I can't comment on how the aspects of the algorithms we implement compare to the aspects of the ones that it does.

**Comment by pradeepdev-1995** [comment]
@scotthlee . I have a dataset containing a target(say **Status**) column with labels **PASS** and **FAIL**, also a protected attribute ```Gender``` with unique values **Male** and **Female**.

So according to this repo code, is it just making Target labels( **PASS** and **FAIL**)  independent of the protected attribute ```Gender``` 
  or 
it is internally considering anything like that ```Female``` is the privileged value and ```Male``` is non-privileged, anything like that? Or user has the option to provide such conditions explicitly to the algorithm?

**Comment by scotthlee** [comment]
Sort of! For the code to be useful, you'd really need third variable--something like `Predicted_Status`, with the two options being `PASS` and `FAIL`, just like the existing target variable--that the algorithm could adjust. In that scenario, if you didn't know whether someone who truly pass or fail, and you wanted to take some action based on your prediction that they would pass or fail, the algorithm would make sure that your predictions would be equal across genders, conditional on underlying gender-wise probabilities of success (for equalized odds, which is the main metric for binary adjustments like that). Basically, if there's no predictor, and you only have `Status` and `Gender`, then the algorithm won't help. :) Also there's nothing that considers which group is privileged or not--that's a feature of the original paper, and so we kept it here.
